### ISSUE TITLE
Looks like the analyzer can't detect stop bits correctly

### ISSUE THREAD

**Issue by webhdx** [jefflongo/GameCubeControllerAnalyzer#2]
I was about to write my own PulseView analyzer for JoyBus protocol but noticed someone already made one for Logic. Neat!

I gave it a try but there seems to be a problem with command stop bits. It handles console command stop bits as 1's and parses them with following bits as the data:

![image](https://user-images.githubusercontent.com/10212760/143502602-faa80fb1-47e1-4264-a496-c102aed1b3e4.png)

Command: 0x00
Response: 0xd40000 but should be 0xa80000

I assume, based on the screenshot from the repo that you just count the time from last rising edge and when it's longer than 4us it identifies it as a stop bit. This is not going to work with some devices i.e. Wavebird receiver because the response can occur immediately. 
Another idea that comes to my mind is that you can use known command lengths from the list here: https://sites.google.com/site/consoleprotocols/home/nintendo-joy-bus-documentation/gamecube-controller?authuser=0 and just cross check where the command should end. This is not perfect because custom devices like https://github.com/Aurelio92/GCPlus-2.0 use extra commands.

My setup:
- the cheapest Chinese 8 channel 24MHz logic analyzer based off Saleae Logic
- Mac OS 11.5.2
- Logic 1.2.18
- Wavebird wireless receiver

**Comment by jefflongo** [comment]
Interesting, I didn't know this detail about the wavebird receiver. I'm not opposed to the idea of decoding the command and expecting the stop bit based on the command, the current behavior could be a fallback in the event of the command not matching any known commands. I don't consider custom devices implementing their own custom commands over the interface as something that should be supported. At some point you either have to use timing to determine a stop bit or the command itself. I will look into implementing this.

**Comment by jefflongo** [comment]
This should be fixed as of [2889b90](https://github.com/jefflongo/GameCubeControllerAnalyzer/commit/2889b906616a0fea4aae2909ac4fa0d047a28922)
